### ISSUE TITLE
请问下如何指定样式为，非活跃和活跃的指示器都是圆形矩形？

### ISSUE THREAD

**Issue by CoderWeiLee** [Code-TanJX/JXPageControl#1]
目前看到指定不同的样式是通过创建时，指定不同的子类型来确定的，如何指定非活跃和活跃的指示器都是圆形矩形呢？

**Comment by Coder-TanJX** [comment]
请问你知道怎么设置了吗? 
设置指示器的宽高一样就是圆形. 
如果还没解决可以加我微信或QQ, 方便帮到你.(WX/QQ:346417517)
