### ISSUE TITLE
指示器间距问题

### ISSUE THREAD

**Issue by ZxLeo** [Code-TanJX/JXPageControl#2]
活跃指示器宽度和非活跃指示器宽度不一致时 间距有问题
<img width="458" alt="截屏2021-01-04 下午1 36 35" src="https://user-images.githubusercontent.com/22698046/103504265-e25e7e00-4e91-11eb-9dbb-d28f5128ca96.png">

**Comment by Coder-TanJX** [comment]
我设计的是以每个指示器的中心做为间距来布局的，让每个指示器中心的间距相同，
这样其中两个指示器交换动画时，其他指示器可以不移动，所以你说的问题和我的设计有些冲突。
每个指示器之间中心点的的间距是以：最宽元素的宽度maxIndicatorSize.width + 固定间距columnSpacing。
你可以考虑将columnSpacing设为小值（比如0.0、-5.0 。。。），这样看起来不这么明显。希望能帮到你。

<img width="910" alt="WeChat1" src="https://user-images.githubusercontent.com/19760428/103509019-273be200-4e9d-11eb-955e-8348cf45d16f.png">
